name: Create main promotion pull request
on:
  push:
    branches:
      - testing
jobs:
  PR-to-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: prod
      - name: Reset dev branch
        run: |
          git fetch origin testing:testing
          git reset --hard testing
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit: "creating pull request for dev branch change"
          branch: testing

