name: Create production promotion pull request-test
on:
  push:
    branches:
      - dev
jobs:
  PR-to-Main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Reset dev branch
        run: |
          git fetch origin dev:dev
          git reset --hard dev
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: dev
