name: Actions workflow
on: [push]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
           pwd
           ls
           ls -lart
      - name: checkout
        uses: actions/checkout@v1
      - name: after checkout
        run: |
            pwd
            ls -lart
      - name: JS actions
        uses: actions/hello-world-javascript-action@v1 # using publically available actions
        id: greet
        with: 
          who-to-greet: John DR # input to the action
      - name: Log the greet
        run: echo "${{steps.greet.outputs.time}}". #display the output using the step Id 
