name: Env vars
on: push
env:
  WF_ENV: Avaible to all jobs
  
jobs:
  log-env:
    runs-on: ubuntu-latest
    env: 
      JOB_ENV: Available to all steps 
    steps:
    - name: Log env vars
      run: |
          echo ${WF_ENV}
          echo ${JOB_ENV}
          
# We can set the env for step level,job level and global for the workflow. Also we have the common global vars by Github.
