name: shell commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
     - name: echo string
       run: echo "hello"
     - name: Python command
       run: python --version
  run-windows-command:
    runs-on: windows-latest
    needs: ["run-shell-command"] # creating dependency jobs
    steps: 
     - name: Dir
       run: Get-Location
     - name: pwd
       run: pwd
       shell: bash
